### ISSUE TITLE
caffe version

### ISSUE THREAD

**Issue by kingvision** [techieinhouse/caffe_face#1]
HI:
   Thanks you for your code. I want to use caffe to extract face feature. my caffe version is rc, which was released in 09,2014. can i use your code extract the face feature?

thanks

**Comment by techieinhouse** [comment]
hi ,
 you can not extract features using my code. The code just takes the value from last layer of the network (softmax layer in my case) to identify the class. The feature extraction in my case was done by fc7 layer in the network itself. The code just reads the output of the network layer. I am not sure but i think  by comparing it with this python code http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb. you can try to modify it to read the output of the extraction layer and play with it.

 Also ,if you haven't came across this already, try the following link  ,you can modify and make use of  this http://caffe.berkeleyvision.org/gathered/examples/feature_extraction.html to extract features and then use some classifier.
